lib/microlog_web/router.ex
defmodule MicroLogWeb.Router do
  use MicroLogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MicroLogWeb do
    pipe_through [:browser, :authenticate_user]

    # forward?
    get "/", PageController, :home

    get "/home", PageController, :home
    get "/help", PageController, :help
    get "/about", PageController, :about
    get "/contact", PageController, :contact

    get "/signup", UserController, :new
    get "/login", SessionController, :new

    resources "/users", UserController, only: [:create]
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/", MicroLogWeb do
    pipe_through [:browser, :authenticate_user, :require_authentication]

    resources "/users", UserController, except: [:create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", MicroLogWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MicroLogWeb.Telemetry
    end
  end

  defp authenticate_user(conn, _) do
    case get_session(conn, :user_id) do
      nil ->
        conn

      user_id ->
        assign(conn, :current_user, MicroLog.Accounts.get_user!(user_id))
    end
  end

  def require_authentication(conn, _) do
    case Map.get(conn.assigns, :current_user) do
      %MicroLog.Accounts.User{} ->
        conn

      _ ->
        conn
        |> put_flash(:info, "Please login to access this page.")
        |> redirect(to: "/login")
        |> halt
    end
  end
end

lib/microlog_web/views/layout_view.ex
defmodule MicroLogWeb.LayoutView do
  use MicroLogWeb, :view

  def title(conn) do
    case conn.assigns do
      %{title: title} -> "#{title} | Phoenix Sample App"
      _ -> "Phoenix Sample App"
    end
  end

  def headers(conn) do
    conn.req_headers
    |> Enum.filter(fn {k, _} -> k != "cookie" end)
    |> Enum.map(fn {k, v} -> {transform_header_key(k), v} end)
  end

  defp transform_header_key("dnt") do
    "DNT"
  end

  defp transform_header_key(string) do
    string
    |> String.split("-")
    |> Enum.map(fn s -> String.capitalize(s) end)
    |> Enum.join("-")
  end
end

lib/microlog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <%= render "head.html", Map.put(assigns, :conn, @conn) %>
  <body>
    <div class='container'>
      <%= render "header.html", Map.put(assigns, :conn, @conn) %>
      <main role="main" class="container mt-4">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= @inner_content %>
      </main>
      <%= render "footer.html", Map.put(assigns, :conn, @conn) %>
    </div>
  </body>
</html>

lib/microlog_web/templates/layout/footer.html.eex
<footer class="footer mt-4">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <%= render "params.html", Map.put(assigns, :params, @conn.params) %>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <%= render "headers.html", Map.put(assigns, :headers, headers(@conn)) %>
      </div>
    </div>
    <div class="row align-items-center justify-content-between">
      <div class="col-auto">
        <div class="row">
          <div class="col-auto">
            <small>
              <a href="https://hexdocs.pm/phoenix/overview.html">
                Get started with Phoenix
              </a>
            </small>
          </div>
        </div>
        <div class="row">
          <div class="col-auto">
            <small>
              This application is inspired by
              <a href="http://www.michaelhartl.com/">Michael Hartl</a>'s
              <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
            </small>
          </div>
        </div>
      </div>
      <div class="col-auto">
        <nav>
          <ul class="list-group list-group-horizontal">
            <li class="list-group-item"><%= link "About", to: "/about" %></li>
            <li class="list-group-item"><%= link "Contact", to: "/contact" %></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li class="list-group-item">
                <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</footer>

lib/microlog_web/templates/layout/head.html.eex
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title><%= title(@conn) %></title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</head>

lib/microlog_web/templates/layout/header.html.eex
<header>
  <nav role="navigation" class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
    <a href="https://github.com/gowda/microlog.elixir.git" class="navbar-brand">
      Phoenix Sample App
    </a>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link "Home", to: "/home", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link "Help", to: "/help", class: "nav-link" %>
      </li>
      <%= if Map.has_key?(@conn.assigns, :current_user) do %>
        <li class="nav-item">
          <%= link "Settings", to: Routes.user_path(@conn, :edit, @current_user.id), class: "nav-link" %>
        </li>
        <%= form_for @conn, Routes.session_path(@conn, :delete), [method: :delete, as: :user], fn _ -> %>
          <li class="nav-item">
            <%= submit "Logout", to: Routes.session_path(@conn, :delete), class: "nav-link", style: "background-color: transparent; border: none;" %>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link "Login", to: Routes.session_path(@conn, :new), class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

lib/microlog_web/templates/layout/headers.html.eex
<div class="row">
  <div class="col">
    <div class="row">
      <div class="col">
        <h4>Headers</h4>
      </div>
    </div>
    <dl class="row">
    <%= for {k, v} <- @headers do %>
      <dt class="col-sm-3"><%= k %><dt>
      <dd class="col-sm-9"><%= v %></dd>
    <% end %>
    </dl>
  </div>
</div>

lib/microlog_web/templates/layout/params.html.eex
<div class="row">
  <div class="col">
    <div class="row">
      <div class="col">
        <h4>Params</h4>
      </div>
    </div>
    <dl class="row">
    <%= for {k, v} <- @params do %>
      <dt class="col-sm-3"><%= k %><dt>
      <dd class="col-sm-9"><%= Jason.encode!(v) %></dd>
    <% end %>
    </dl>
  </div>
</div>